# Site settings
title: Bridging Innovation and Business Value
email: a.gigante@gmail.com
description: "<p>As a Principal Product Manager, I transform complex innovation, particularly in <strong>AI</strong> and <strong>Data Visualization</strong>, into measurable business value through secure and user-centric solutions. With over 13 years of experience, I drive digital product initiatives from concept to customer adoption, delivering tangible results.</p>"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: agigante80
linkedin_username: agigante

# Build settings
markdown: kramdown
